# Usage: KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen list
---
driver:
  name: localhost

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10

suites:
  - name: safari_test
    run_list:
      - recipe[safari_test::extension]
      - recipe[safari_test::version]
    attributes:
      safari_test:
        user: travis
