language: ruby

rvm:
  - 2.1.0

os:
  - osx

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle update

script:
  - chef exec bundle exec rake
  - chef exec bundle exec kitchen test
