matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: ruby
      rvm:
        - 2.1.0
    - os: osx
      osx_image: xcode7.2
      language: ruby
      rvm:
        - 2.1.0
    - os: osx
      osx_image: xcode7.1
      language: ruby
      rvm:
        - 2.1.0
    - os: osx
      osx_image: xcode7
      language: ruby
      rvm:
        - 2.1.0
    - os: osx
      osx_image: xcode6.4
      language: ruby
      rvm:
        - 2.1.0
    - os: osx
      osx_image: xcode6.3
      language: ruby
      rvm:
        - 2.1.0
    - os: osx
      osx_image: xcode6.2
      language: ruby
      rvm:
        - 2.1.0

install:
  - bundle update

script:
  - bundle exec rake
  - KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen test
